// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkS674i9jvEMc3vQnoIeb-5U6xu7RAjF8',
    appId: '1:71569162763:android:26e7de8fae14a2c6befd0e',
    messagingSenderId: '71569162763',
    projectId: 'teste-yourcloset',
    storageBucket: 'teste-yourcloset.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN5ZCpHR2DsYGdP6kb_sliAPK4tNUk1Zw',
    appId: '1:71569162763:ios:1093b4279566411abefd0e',
    messagingSenderId: '71569162763',
    projectId: 'teste-yourcloset',
    storageBucket: 'teste-yourcloset.appspot.com',
    iosBundleId: 'com.example.yourCloset',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN5ZCpHR2DsYGdP6kb_sliAPK4tNUk1Zw',
    appId: '1:71569162763:ios:fb4abc448730437cbefd0e',
    messagingSenderId: '71569162763',
    projectId: 'teste-yourcloset',
    storageBucket: 'teste-yourcloset.appspot.com',
    iosBundleId: 'com.example.yourCloset.RunnerTests',
  );
}
